# Generated by Django 5.1.6 on 2025-03-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_alter_claim_status_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
