# Generated by Django 5.1.6 on 2025-03-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_policy_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='treatment_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
